apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /giropopsNginx
      name: nginx-emptydir
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  - image: busybox
    name: busybox
    volumeMounts:
    - mountPath: /giropopsBusybox
      name: busybox-emptydir
    args:
    - sleep
    - "1800"
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  volumes:
  - name: nginx-emptydir
    emptyDir:
      sizeLimit: 128Mi
  - name: busybox-emptydir
    emptyDir:
      sizeLimit: 128Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
